<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copyright">
    <div class="copyright_text" style="width: 1240px; margin: 0 auto;"><?php echo $this->getCopyright() ?></div>
</div>

<!-- Go to www.addthis.com/dashboard to customize your tools --> 
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54931d8e691caf8a"></script> 

<?php /* @escapeNotVerified */ echo $block->getMiscellaneousHtml();