<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php $index = 0; ?>
            <?php $activeTabIndex = false; ?>
            <?php $activeTabFound = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content">
                        <?php $wrapOptions = true; ?>
                    <?php endif; ?>
                        <?php $filterName = str_replace(' ','-', strtolower($filter->getName())); ?>
                        <?php if($filterName == 'brand') { $activeTabIndex = $index; $activeTabFound = true; } ?>
                        <div data-role="collapsible" class="filter-options-item">
                            <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                            <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                        </div>
                    <?php $index++; ?>
                <?php endif; ?>
            <?php  endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>

            <script>
                require([
                    'jquery',
                    'accordion'
                ], function ($) {
                    $(function () {
                        $('#narrow-by-list')
                            .accordion({
                                "openedState": "active",
                                "collapsible": true,
                                <?php if($activeTabFound):  ?>
                                    "active": "<?php echo $activeTabIndex; ?>",
                                <?php else: ?>
                                    "active": false,
                                <?php endif; ?>
                                "multipleCollapsible": false
                            });
                    });
                });
            </script>

            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>

        </div>
    </div>
<?php endif; ?>
